version: '3'
services:
    web:
        image: nginx:latest
        environment:
            - TZ=Asia/Makassar
        ports: 
            - 80:80
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app/OpenSID:/var/www/html
        restart: always
        depends_on:
            - php
            - mariadb
        networks:
            - frontend

    php:
        build:
            context: .
            dockerfile: conf.d/PHP.Dockerfile
        environment:
            - TZ=Asia/Makassar
        volumes:
            - ./app/OpenSID:/var/www/html
        expose:
            - 9000
        restart: always
        depends_on:
            - mariadb
        networks:
            - frontend
            - backend

    mariadb:
        image: lscr.io/linuxserver/mariadb:latest
        restart: always
#       PUID=1002 adalah user 'adminsid' dan PGID=33 adalah group 'www-data'
#       gunakan perintah 'id' untuk memastikannya
        environment:
            - TZ=Asia/Makassar
            - PUID=1002
            - PGID=33
            - MYSQL_ROOT_PASSWORD=secret            
            - MYSQL_DATABASE=sid
            - MYSQL_USER=adminsid
            - MYSQL_PASSWORD=rahasia
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./mariadb_data:/config
        networks:
            - backend

volumes:
    mariadb_data:

networks:
    frontend:
    backend:
